//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameInfo
    {
        public int GameID { get; set; }
        public string GameTitle { get; set; }
        public string GameType { get; set; }
        public System.DateTime GameDate { get; set; }
        public int GameTurns { get; set; }
        public string GameServer { get; set; }
        public int GameSpectators { get; set; }
    }
}
